blueprint:
  name: Control light by motion
  description: Controls the light with motion sensors and the available day light
  domain: automation
  source_url: https://github.com/paule96/HomeAssistantConfiguration/blob/main/MotionLightsBlueprint.yaaml
  author: paule96
  input:
    room:
      selector:
        area:
      name: Room
    delay:
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: minutes
      name: Delay
    light_level:
      name: Light Level Sensor
      selector:
        entity:
          filter:
            - domain: sensor
    light_level_to_turn_on:
      name: Light Level to turn on
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: lx
mode: restart
trigger_variables:
  var_room: !input room
triggers:
  trigger: template
  value_template: >- 
    {{ (expand(area_entities(var_room))|selectattr('attributes.device_class','eq','occupancy') | selectattr('state', 'eq', 'on') | list | count) > 0 }}
conditions:
  - condition: numeric_state
    entity_id: !input light_level
    below: !input light_level_to_turn_on
actions:
  - variables:
      var_room: !input room
      var_delay: !input delay
  - alias: Turn on light
    action: light.turn_on
    target:
      area_id: "{{ var_room }}"
  - wait_template: "{{ (expand(area_entities(var_room))|selectattr('attributes.device_class','eq','occupancy')| selectattr('state', 'eq', 'on') | list | count) == 0 }}"
    continue_on_timeout: true
  - delay: "{{ var_delay }}"
  - alias: Turn off light
    action: light.turn_off
    target:
      area_id: "{{ var_room }}"