blueprint:
  name: Switch buttons
  description: Controls the light with switches. Maybe at some point more then just lights
  domain: automation
  source_url: https://raw.githubusercontent.com/paule96/HomeAssistantConfiguration/refs/heads/main/SwitchBlueprint.yaml
  author: paule96
  input:
    room:
      selector:
        area:
      name: Room
      description: The room that should react on motion
    brightness_step_pct:
      default: 15
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
      name: Steps the light will be increased
      description: Defines a number how much the light will increased or decrease. The number is readed as a percentage.
mode: restart
trigger_variables:
  var_room: !input room
triggers:
  - trigger: event
    event_type: zha_event
    event_data:
      command: off_triple_press
    id: tripple_press
  - trigger: event
    event_type: zha_event
    event_data:
      command: on_press
    id: on_press
  - trigger: event
    event_type: zha_event
    event_data:
      command: down_short_release
    id: on_down_short_press
  - trigger: event
    event_type: zha_event
    event_data:
      command: down_press
    id: on_down_press
  - trigger: event
    event_type: zha_event
    event_data:
      command: up_short_release
    id: on_up_short_press
  - trigger: event
    event_type: zha_event
    event_data:
      command: up_press
    id: on_up_press
  - trigger: event
    event_type: zha_event
    event_data:
      command: off_press
    id: off_press
conditions:
  - condition: template
    value_template:  >-  
      {{ area_id(trigger.event.data.device_id) == var_room }}
    enabled: true
actions:
  - variables:
      area: "{{area_id(trigger.event.data.device_id)}}"
      brightness_step_pct: !input brightness_step_pct
  - choose:
      - conditions:
          - condition: trigger
            id:
              - tripple_press
        sequence:
          - action: light.turn_off
            metadata: {}
            data: {}
            entity_id: all
      - conditions:
          - condition: trigger
            id:
              - on_press
        sequence:
          - action: light.turn_on
            metadata: {}
            data: {}
            target: 
              area_id: "{{ area }}"
      - conditions:
          - condition: trigger
            id:
              - off_press
        sequence:
          - action: light.turn_off
            metadata: {}
            data: {}
            target: 
              area_id: "{{ area }}"
      - conditions:
          - condition: trigger
            id:
              - on_up_press
              - on_up_short_press
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              brightness_step_pct: {{brightness_step_pct}}
            target:
              area_id: "{{ area }}"
            alias: Increase light
      - conditions:
          - condition: trigger
            id:
              - on_down_press
              - on_down_short_press
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              brightness_step_pct: -{{brightness_step_pct}}
            target:
              area_id: "{{ area }}"
