blueprint:
  name: Switch buttons
  description: Controls the light with switches. Maybe at some point more then just lights
  domain: automation
  source_url: https://raw.githubusercontent.com/paule96/HomeAssistantConfiguration/refs/heads/main/SwitchBlueprint.yaml
  author: paule96
  input:
    room:
      selector:
        area:
      name: Room
      description: The room that should react on motion
mode: restart
trigger_variables:
  var_room: !input room
triggers:
  - trigger: event
    event_type: zha_event
    event_data:
      command: on_triple_press
    id: tripple_press
  - trigger: event
    event_type: zha_event
    event_data:
      command: on_press
    id: on_press
  - trigger: event
    event_type: zha_event
    event_data:
      command: off_press
    id: off_press
conditions:
  - condition: template
    value_template: "{{ area_name(trigger.event.data.device_id) == var_room }}"
    enabled: true
actions:
  - variables:
      area: "{{area_name(trigger.event.data.device_id)}}"
  - choose:
      - conditions:
          - condition: trigger
            id:
              - tripple_press
        sequence:
          - action: light.turn_off
            metadata: {}
            data: {}
            entity_id: all
      - conditions:
          - condition: trigger
            id:
              - on_press
        sequence:
          - action: light.turn_on
            metadata: {}
            data: {}
            target: 
              area_id: "{{ area }}"
      - conditions:
          - condition: trigger
            id:
              - off_press
        sequence:
          - action: light.turn_off
            metadata: {}
            data: {}
            target: 
              area_id: "{{ area }}"
